### PR TITLE
Vote Page Bug Fixes

### LINKED ISSUE #391: Prop 30 displays incorrect "against" vote count
https://nouns.wtf/vote/30 displays 2 votes against the proposal, when it should be 5. 2 is the number of owners of the 5 Nouns at time of voting.

This bug was present before the new UI introduced in PR #379 as seen in this screenshot
image

### PR DESCRIPTION
**Pull request by solimander**
This PR resolves #391 and #392.

For #391, the vote counts were correct, but the Noun images were not. We were pulling current Noun delegate information, rather than details from the time the proposal was created. The quick fix for this issue requires two calls - one to fetch the voter ids and a second time-travel request to fetch the Noun information from the proposal creation block. This can be reduced to a single call via a larger change to the subgraph in the future.

### CODE REVIEW

File: packages/nouns-webapp/src/wrappers/subgraph.ts [hunk 1]
```diff
@@ -19,6 +19,28 @@ export interface IBid {
...
+  voter: {
+    id: string;
+  };
+}
+
+export interface ProposalVotes {
+  votes: ProposalVote[];
+}
+
+export interface DelegateNouns {
```
Comment (bcjgit) [inline packages/nouns-webapp/src/wrappers/subgraph.ts:33]: Non-blocking nit:

Assuming I'm understanding this correctly this represents 1 address (`id`) to whom a series of nouns has been delegates (`nounsRepresented`). If that's true, I wonder if the name could be changed to make it clear this is the delegated address vs being a Noun or something.

File: packages/nouns-webapp/src/utils/getNounsVotes.ts [hunk 2]
```diff
@@ -1,14 +1,15 @@
+interface NounVote {
```
Comment (bcjgit) [inline packages/nouns-webapp/src/utils/getNounsVotes.ts:1]: nit:

Similar comment to the one I made on the `DelegateNouns` interface ... this isn't _really_ a Noun vote right? It's the votes cast by a delegate with the represented Nouns ... right? Again, not blocking but wonder if naming could make this clearer.

**Review by bcjgit — APPROVED** [review]
Left a few non-blocking comments but overall lgtm. Thanks for this!
